/*	Archivo: union_xdr.c
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "union.h"

bool_t
xdr_U (XDR *xdrs, U *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->flag))
		 return FALSE;
	switch (objp->flag) {
	case 1:
		 if (!xdr_int (xdrs, &objp->U_u.i))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_double (xdrs, &objp->U_u.d))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
