/*	Archivo:	union_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "union.h"

U *
funcion_1_svc(int arg1,  struct svc_req *rqstp)
{
	static U  result;
	/* agregado */
	/* EN CASO DE QUE RESTO DE DIVISION ENTERA POR 3
	 * SEA: 0  ==> ASIGNA: result.flag = 1
	 * SEA: 1  ==> ASIGNA: result.flag = 2
	 * SEA: 2  ==> ASIGNA: result.flag = 0
	 **/
	switch(arg1 % 3){
		case 0:
			result.U_u.i = 10;
			result.flag = 1; /* ? */ 
			break;
		case 1:	
			result.U_u.d = 3.14;
			result.flag = 2; /* ? */
			break;
		case 2:	
			result.flag = 0; /* ? */
			break;
	}
	/*----------*/
	return &result;
}
/*Fin del archivo:	union_server.c */
