/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UNION_H_RPCGEN
#define _UNION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct U {
	int flag;
	union {
		int i;
		double d;
	} U_u;
};
typedef struct U U;

#define UNION 0x20000004
#define VUNION 1

#if defined(__STDC__) || defined(__cplusplus)
#define funcion 1
extern  U * funcion_1(int , CLIENT *);
extern  U * funcion_1_svc(int , struct svc_req *);
extern int union_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define funcion 1
extern  U * funcion_1();
extern  U * funcion_1_svc();
extern int union_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_U (XDR *, U*);

#else /* K&R C */
extern bool_t xdr_U ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UNION_H_RPCGEN */
